# Homework #2

- Date: 2024.03.17
- Due Date: 2024.04.07

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
data = pd.read_csv("../Diabetes Classification.csv")

In [8]:
data.columns

Index(['Unnamed: 0', 'Age', 'Gender', 'BMI', 'Chol', 'TG', 'HDL', 'LDL', 'Cr',
       'BUN', 'Diagnosis'],
      dtype='object')

[함께해보기] "Diabetes Classificiation.csv" 파일을 불러오고, 남성과 여성의 평균 나이를 출력하세요.
- 남성 최대, 최소 나이도 구해보세요
- 여성 최대, 최소 나이도 구해보세요

In [22]:
data_male = data[data['Gender']=='M']
data_female = data[data['Gender']=='F']
print(data_male)

      Unnamed: 0  Age Gender  BMI  Chol    TG       HDL       LDL    Cr   BUN  \
1              1   26      M   23  3.70  1.40  1.100000  2.100000  62.0  4.50
2              2   33      M   21  4.90  1.00  0.800000  2.000000  46.0  7.10
5              5   48      M   24  2.90  0.80  0.900000  1.600000  47.0  4.70
6              6   43      M   21  3.80  0.90  2.400000  3.700000  67.0  2.60
13            13   50      M   21  3.60  1.10  1.000000  2.100000  74.0  5.50
...          ...  ...    ...  ...   ...   ...       ...       ...   ...   ...
5125        5125   77      M   22  4.02  1.28  1.230000  2.250000  60.6  4.34
5126        5126   31      M   25  4.00  2.00  4.860753  4.860753  88.0  5.00
5127        5127   54      M   23  5.00  1.50  1.240000  2.980000  77.0  3.50
5129        5129   67      M   24  3.89  1.38  1.140000  2.170000  70.6  4.73
5131        5131   37      M   34  5.42  2.66  1.080000  2.870000  75.5  4.61

      Diagnosis
1             0
2             0
5             0
6             0
13            0
...         ...
5125          1
5126          1
5127          1
5129          1
5131          1

[3256 rows x 11 columns]

In [31]:
print(np.mean(data_male['Age']))
print(np.mean(data_female['Age']))

print(np.max(data_male['Age']))
print(np.max(data_female['Age']))

print(np.min(data_male['Age']))
print(np.min(data_female['Age']))

48.84244471744472
49.1344
91
93
22
20

[문제1] 30대 이상 여성의 평균 BMI와 Chol 수치는 얼마인가요?

In [35]:
#female_age = data_female['Age']
#age_list_f= list(female_age)
#print(age_list_f)

[50, 45, 50, 32, 31, 33, 30, 45, 50, 50, 49, 49, 49, 42, 33, 39, 30, 44, 48, 47, 39, 38, 41, 45, 44, 33, 47, 45, 47, 50, 50, 49, 50, 49, 44, 48, 35, 35, 42, 31, 41, 43, 44, 35, 30, 50, 57, 50, 35, 25, 40, 40, 60, 77, 44, 54, 50, 59, 43, 49, 49, 39, 39, 30, 50, 49, 33, 40, 35, 48, 50, 48, 46, 54, 49, 45, 47, 42, 45, 63, 44, 49, 44, 33, 48, 47, 33, 33, 28, 39, 49, 56, 59, 54, 60, 60, 61, 55, 63, 52, 55, 51, 60, 53, 54, 66, 52, 61, 56, 66, 56, 59, 56, 55, 61, 51, 55, 51, 61, 55, 58, 56, 55, 60, 51, 68, 54, 54, 54, 54, 61, 63, 55, 52, 51, 58, 66, 60, 52, 56, 55, 59, 57, 54, 61, 55, 51, 58, 55, 54, 58, 63, 61, 59, 54, 57, 60, 52, 63, 58, 52, 51, 58, 54, 69, 51, 56, 64, 56, 54, 60, 60, 61, 54, 60, 51, 58, 56, 60, 56, 59, 57, 54, 53, 60, 63, 52, 58, 64, 53, 55, 56, 60, 52, 56, 59, 57, 67, 60, 61, 61, 55, 61, 51, 55, 55, 53, 61, 55, 55, 57, 60, 70, 79, 54, 66, 52, 56, 55, 54, 60, 60, 54, 62, 67, 55, 54, 55, 53, 61, 60, 59, 51, 56, 54, 63, 55, 55, 60, 52, 51, 56, 54, 61, 52, 64, 54, 60, 59, 55, 55, 58, 55, 52, 51, 55, 53, 52, 56, 68, 59, 64, 54, 55, 55, 60, 61, 55, 55, 58, 54, 60, 52, 59, 54, 54, 55, 57, 60, 61, 63, 58, 60, 60, 64, 56, 59, 55, 57, 63, 68, 69, 55, 54, 61, 60, 56, 67, 58, 42, 53, 73, 44, 30, 45, 60, 55, 55, 55, 59, 59, 54, 61, 52, 42, 60, 56, 56, 61, 55, 52, 55, 54, 56, 55, 76, 31, 35, 60, 44, 51, 36, 36, 56, 55, 55, 55, 55, 63, 55, 61, 61, 51, 53, 62, 60, 55, 50, 50, 34, 28, 35, 40, 35, 65, 60, 70, 20, 54, 60, 75, 57, 40, 46, 37, 38, 26, 42, 34, 85, 30, 27, 68, 50, 29, 41, 40, 35, 36, 33, 30, 53, 43, 41, 40, 53, 59, 26, 42, 28, 34, 42, 42, 36, 46, 27, 40, 53, 27, 37, 69, 43, 42, 33, 38, 34, 33, 40, 29, 32, 54, 36, 51, 37, 34, 45, 25, 34, 39, 46, 46, 26, 26, 46, 34, 49, 41, 26, 51, 40, 34, 29, 50, 50, 55, 31, 30, 29, 70, 33, 52, 43, 30, 51, 55, 44, 69, 69, 62, 61, 51, 76, 54, 44, 32, 38, 43, 31, 44, 67, 38, 40, 55, 72, 60, 26, 35, 31, 38, 85, 35, 49, 37, 40, 29, 24, 32, 35, 36, 37, 64, 45, 35, 32, 27, 39, 25, 29, 38, 52, 36, 29, 61, 35, 30, 30, 31, 34, 34, 28, 73, 59, 39, 31, 43, 32, 63, 45, 38, 38, 78, 45, 42, 70, 28, 67, 46, 49, 52, 46, 34, 28, 69, 53, 31, 47, 38, 34, 29, 58, 31, 70, 47, 76, 60, 33, 40, 27, 65, 35, 35, 35, 30, 51, 52, 33, 27, 70, 39, 34, 46, 48, 57, 66, 47, 48, 40, 26, 43, 45, 30, 53, 33, 34, 38, 28, 31, 48, 35, 37, 30, 36, 41, 35, 50, 29, 52, 36, 38, 42, 42, 32, 41, 49, 35, 28, 33, 42, 37, 55, 34, 47, 31, 42, 25, 31, 33, 53, 42, 50, 49, 34, 45, 58, 50, 57, 32, 49, 44, 27, 63, 54, 27, 33, 43, 56, 63, 41, 43, 36, 30, 58, 37, 46, 28, 36, 37, 50, 34, 30, 27, 59, 42, 40, 72, 39, 44, 58, 36, 26, 57, 46, 39, 46, 48, 31, 47, 67, 40, 37, 46, 34, 31, 35, 35, 55, 29, 48, 28, 31, 68, 61, 29, 41, 27, 28, 28, 34, 56, 64, 35, 34, 32, 50, 41, 31, 37, 37, 71, 38, 61, 54, 50, 38, 37, 57, 54, 51, 34, 34, 66, 54, 43, 30, 31, 48, 61, 41, 57, 43, 29, 35, 36, 38, 29, 29, 28, 56, 43, 34, 36, 28, 34, 29, 32, 48, 47, 44, 45, 26, 53, 27, 41, 40, 42, 47, 62, 38, 75, 42, 37, 27, 39, 51, 30, 35, 42, 68, 53, 34, 63, 44, 34, 34, 39, 41, 44, 35, 35, 49, 46, 45, 35, 46, 53, 31, 65, 56, 36, 24, 38, 62, 42, 57, 43, 55, 43, 34, 29, 36, 45, 37, 37, 38, 34, 34, 28, 45, 68, 34, 29, 35, 54, 61, 34, 36, 48, 69, 46, 27, 29, 56, 42, 52, 28, 46, 26, 24, 46, 44, 65, 44, 37, 32, 41, 47, 66, 66, 35, 47, 36, 46, 47, 29, 38, 48, 30, 33, 40, 38, 40, 29, 58, 32, 50, 33, 35, 33, 37, 64, 37, 69, 64, 25, 29, 27, 48, 47, 80, 41, 28, 35, 55, 71, 41, 29, 48, 49, 76, 60, 59, 26, 32, 35, 32, 34, 48, 44, 40, 51, 28, 37, 36, 41, 49, 54, 56, 50, 66, 65, 38, 73, 29, 36, 30, 59, 41, 43, 50, 33, 35, 28, 24, 66, 44, 63, 56, 37, 25, 42, 37, 71, 50, 31, 42, 68, 29, 33, 32, 42, 41, 29, 47, 39, 67, 70, 41, 67, 47, 33, 66, 32, 42, 35, 68, 40, 55, 28, 59, 44, 41, 28, 35, 34, 34, 27, 80, 27, 45, 36, 34, 44, 51, 42, 52, 39, 72, 33, 34, 28, 29, 59, 57, 35, 33, 52, 45, 32, 49, 30, 36, 30, 40, 59, 33, 61, 38, 32, 40, 25, 34, 43, 32, 49, 55, 37, 29, 30, 37, 40, 35, 58, 27, 28, 29, 49, 32, 35, 30, 43, 53, 52, 36, 39, 59, 64, 33, 31, 46, 49, 37, 31, 73, 27, 44, 49, 58, 43, 35, 29, 50, 54, 35, 36, 40, 40, 65, 64, 67, 51, 47, 35, 64, 35, 37, 46, 72, 51, 46, 61, 46, 35, 38, 26, 56, 68, 33, 34, 62, 40, 61, 34, 47, 39, 71, 26, 33, 40, 51, 30, 49, 50, 38, 45, 63, 30, 27, 30, 50, 58, 43, 62, 36, 34, 62, 61, 34, 63, 26, 68, 29, 58, 39, 53, 61, 32, 31, 34, 38, 47, 42, 45, 30, 25, 42, 53, 35, 64, 27, 31, 52, 52, 28, 28, 56, 55, 38, 68, 68, 47, 27, 40, 57, 37, 30, 66, 35, 56, 58, 47, 58, 61, 29, 60, 31, 38, 41, 29, 39, 48, 48, 56, 37, 45, 69, 32, 43, 34, 32, 38, 32, 35, 36, 44, 52, 35, 30, 93, 43, 33, 28, 38, 46, 44, 34, 34, 35, 39, 34, 54, 27, 34, 36, 40, 33, 39, 72, 29, 39, 60, 42, 30, 35, 35, 26, 68, 27, 62, 29, 46, 34, 46, 60, 38, 46, 37, 29, 51, 29, 41, 42, 33, 36, 45, 52, 62, 34, 27, 51, 40, 39, 31, 32, 67, 38, 44, 29, 34, 59, 42, 38, 25, 33, 60, 40, 34, 61, 44, 27, 45, 36, 28, 33, 40, 35, 42, 47, 52, 29, 34, 62, 61, 41, 58, 63, 23, 40, 40, 66, 37, 35, 75, 57, 48, 35, 28, 36, 69, 30, 32, 44, 40, 26, 32, 48, 45, 28, 50, 53, 51, 64, 28, 33, 41, 54, 46, 39, 31, 29, 50, 44, 36, 62, 45, 25, 65, 32, 44, 41, 61, 42, 26, 30, 34, 42, 28, 63, 51, 28, 37, 76, 56, 33, 82, 33, 46, 38, 35, 30, 27, 29, 35, 33, 48, 25, 34, 42, 67, 54, 28, 33, 48, 49, 32, 39, 29, 50, 46, 32, 35, 71, 31, 55, 26, 34, 33, 46, 33, 41, 36, 53, 44, 47, 66, 39, 46, 71, 65, 30, 29, 28, 53, 35, 35, 55, 63, 39, 41, 35, 31, 67, 46, 30, 31, 30, 41, 29, 32, 31, 45, 68, 41, 35, 44, 49, 33, 60, 30, 39, 31, 48, 52, 30, 33, 34, 59, 36, 32, 37, 49, 70, 40, 54, 48, 34, 87, 44, 46, 32, 32, 45, 32, 53, 62, 31, 57, 36, 43, 61, 60, 41, 33, 36, 37, 34, 30, 33, 46, 63, 28, 39, 48, 39, 44, 59, 70, 32, 49, 37, 53, 35, 40, 61, 26, 43, 51, 43, 33, 67, 60, 78, 51, 64, 67, 41, 54, 72, 49, 85, 65, 72, 53, 58, 62, 71, 75, 59, 61, 61, 47, 29, 62, 39, 72, 37, 26, 78, 78, 80, 53, 75, 36, 60, 54, 59, 85, 64, 67, 66, 66, 83, 80, 64, 52, 83, 47, 88, 76, 62, 37, 38, 58, 81, 76, 45, 69, 74, 57, 56, 64, 56, 54, 70, 71, 71, 64, 55, 55, 49, 52, 60, 58, 83, 53, 77, 45, 73, 70, 74, 67, 84, 76, 50, 52, 56, 46, 64, 60, 70, 64, 57, 50, 66, 75, 59, 53, 55, 29, 47, 33, 60, 74, 39, 66, 66, 65, 55, 45, 78, 75, 65, 31, 81, 63, 58, 61, 40, 66, 56, 59, 77, 80, 58, 76, 57, 80, 30, 62, 40, 46, 42, 35, 55, 53, 61, 39, 78, 58, 55, 77, 63, 63, 78, 56, 73, 63, 34, 30, 64, 50, 61, 71, 67, 70, 62, 71, 67, 64, 62, 65, 42, 68, 60, 73, 64, 66, 64, 74, 71, 64, 72, 55, 75, 63, 71, 80, 61, 59, 30, 66, 61, 63, 62, 76, 61, 72, 58, 70, 78, 64, 30, 50, 42, 65, 67, 63, 59, 42, 63, 67, 74, 60, 75, 59, 33, 45, 57, 61, 62, 69, 58, 55, 53, 69, 75, 42, 53, 51, 70, 81, 75, 30, 52, 74, 58, 44, 66, 59, 65, 76, 53, 80, 67, 70, 63, 54, 53, 53, 58, 84, 60, 78, 52, 56, 68, 55, 53, 73, 36, 65, 62, 66, 64, 61, 75, 53, 65, 74, 77, 31, 71, 56, 69, 58, 68, 55, 83, 42, 87, 52, 46, 59, 67, 28, 71, 70, 59, 51, 29, 65, 61, 45, 63, 51, 66, 57, 49, 61, 63, 66, 70, 56, 56, 31, 79, 40, 59, 61, 71, 57, 75, 47, 37, 65, 75, 40, 65, 69, 68, 64, 70, 66, 63, 73, 78, 64, 53, 39, 72, 59, 58, 75, 60, 47, 61, 43, 49, 60, 59, 82, 73, 59, 47, 83, 81, 72, 71, 52, 65, 30, 65, 56, 58, 40, 57, 65, 53, 59, 30, 71, 51, 59, 55, 66, 69, 53, 68, 80, 73, 45, 48, 56, 72, 61, 58, 72, 67, 63, 59, 60, 77, 62, 63, 61, 57, 51, 34, 60, 51, 61, 59, 44, 40, 70, 72, 49, 78, 78, 65, 46, 81, 69, 70, 62, 63, 66, 50, 63, 28, 71, 79, 59, 67, 59, 47, 60, 63, 52, 63, 65, 67, 45, 59, 69, 55, 44, 56, 52, 69, 32, 64, 67, 32, 73, 52, 65, 40, 62, 75, 57, 50, 73, 54, 58, 53, 28, 64, 57, 41, 63, 84, 67, 62, 42, 54, 54, 38, 42, 57, 76, 59, 66, 67, 74, 49, 49, 69, 38, 78, 69, 59, 46, 60, 50, 60]

In [ ]:
#if age_list_f > 30:
    #print(np.mean(data_female['Chol']))
    #print(np.mean(data_female['BMI']))

[문제2] 당뇨병에 걸린 사람(Diagnosis==1)의 남녀 비율은 어떻게 되나요? 평균 연령은 어떻게 되나요?
- 당뇨병에 걸리지 않은 사람들은 총 몇명인가요?
- 당뇨병에 걸리지 않은 남녀 비율은 어떻게 되나요?

[문제3] 당뇨병에 걸린 사람들의 혈액검사 수치 결과와 당뇨병에 걸리지 않은 사람들의 혈액검사 수치 결과는 어떻게 다른가요? 
(자유분석)
- 예) 당뇨병에 걸린 사람들의 콜레스테롤 수치가 당뇨병을 걸리지 않은 사람들의 콜레스테롤 수치보다 *** 이상 높다.